services:
  backend-dev:
    profiles:
      - dev
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - hn-network

  frontend-dev:
    profiles:
      - dev
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - hn-network

  backend-prod:
    profiles:
      - prod
    image: ghcr.io/samayethali/hacker-news-summary-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - hn-network

  frontend-prod:
    profiles:
      - prod
    image: ghcr.io/samayethali/hacker-news-summary-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend-prod
    restart: unless-stopped
    networks:
      - hn-network

networks:
  hn-network:
    driver: bridge
