services:
  backend:
    container_name: backend
    image: ${IMAGE_REPO:-ghcr.io/samayethali/hacker-news-summary-backend}:${IMAGE_TAG:-latest}
    # Development override - will use this instead of image if BUILD_LOCALLY=true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - hn-network

  frontend:
    container_name: frontend
    image: ${IMAGE_REPO:-ghcr.io/samayethali/hacker-news-summary-frontend}:${IMAGE_TAG:-latest}
    # Development override - will use this instead of image if BUILD_LOCALLY=true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hn-network

networks:
  hn-network:
    driver: bridge
