services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-samayethali/hacker-news-summary}-backend:latest
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - hn-network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-samayethali/hacker-news-summary}-frontend:latest
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hn-network

networks:
  hn-network:
    driver: bridge
